import AVFoundation
import Foundation

struct LocalTrack: Identifiable, Codable, Equatable, Sendable {
    let id: UUID
    var title: String
    var filename: String
    var duration: Double
    var url: URL { LocalLibrary.directory.appendingPathComponent(filename) }
}

enum LocalLibrary {
    static var directory: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Afterglow/Imports", isDirectory: true)
    }
    private static var index: URL { directory.appendingPathComponent("library.json") }
    static func read() -> [LocalTrack] {
        guard let data = try? Data(contentsOf: index),
              let tracks = try? JSONDecoder().decode([LocalTrack].self, from: data) else { return [] }
        // Only filenames generated by this app are accepted from the index.
        return tracks.filter {
            !$0.filename.contains("/") && !$0.filename.contains("..") && FileManager.default.fileExists(atPath: $0.url.path)
        }
    }
    static func save(_ tracks: [LocalTrack]) throws {
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try JSONEncoder().encode(tracks).write(to: index, options: .atomic)
    }
    static func importFile(_ original: URL) async throws -> LocalTrack {
        let scoped = original.startAccessingSecurityScopedResource()
        defer { if scoped { original.stopAccessingSecurityScopedResource() } }
        return try await Task.detached(priority: .userInitiated) {
            let id = UUID()
            let destination = directory.appendingPathComponent(id.uuidString).appendingPathExtension(original.pathExtension)
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            do {
                // Copy into the sandbox so playback survives relaunch and security-scope expiration.
                try FileManager.default.copyItem(at: original, to: destination)
                let audio = try AVAudioFile(forReading: destination)
                guard audio.length > 0 else { throw AfterglowError.message("The file is empty.") }
                return LocalTrack(id: id, title: original.deletingPathExtension().lastPathComponent,
                                  filename: destination.lastPathComponent,
                                  duration: Double(audio.length) / audio.processingFormat.sampleRate)
            } catch {
                try? FileManager.default.removeItem(at: destination)
                throw AfterglowError.message("Couldn’t import \(original.lastPathComponent). Choose an unprotected WAV, MP3, AAC, AIFF, or ALAC file. \(error.localizedDescription)")
            }
        }.value
    }
    static func remove(_ track: LocalTrack) throws { try FileManager.default.removeItem(at: track.url) }
}
